### ISSUE TITLE
wrong size in left side panel

### ISSUE THREAD

**Issue by lordkian** [yousefvand/plasmoid-persian-calendar#8] opened 2021-06-17 16:05 UTC
hi.
I'm using Manjaro KDE. The main panel is on the left side. Only month is visible.

**Comment by yousefvand** [comment] 2021-06-17 16:51
Hi, is there enough space on the panel for the widget. Can you attach a screenshot?

**Comment by yousefvand** [comment] 2021-06-22 06:42
Assuming the problem had been lack of enough space on the panel, and the problem is solved, I'm closing this issue.

**Closed by yousefvand** 2021-06-22 06:42 UTC
Labels: question
